# Generated by Django 3.0.8 on 2020-10-27 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_follor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follor',
            new_name='Follow',
        ),
    ]
